services:
  postgres:
    image: postgres:17
    container_name: healthcare-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: healthcare_user
      POSTGRES_PASSWORD: healthcare_password
      POSTGRES_DB: healthcare_analytics

    ports:
      - "5432:5432"

    volumes:
      - healthcare_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U healthcare_user -d healthcare_analytics
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  healthcare_postgres_data: