
healthcare_analytics:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev

dbt_healthcare:
  target: cloud

  outputs:
    cloud:
      type: snowflake
      account: UAINDNN-DN02045
      user: ARTHIANBALAGAN
      password: YOUR_PASSWORD
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: HEALTHCARE_ANALYTICS
      schema: DBT_ARTHI
      threads: 4
      client_session_keep_alive: false